### PR TITLE
offset cluster ids, add index ids to non cluster points

### LINKED ISSUE #97: Add option to Generate IDs for input features
#94 implements index-based ids for the returned cluster nodes. Some GeoJSON input may not have feature ids, or may use string feature ids which do not work with `geojson-vt`. 

### Proposal

`generateLeafIds`: enables generation of ids on the leaf nodes, ensuring uniqueness across leaf nodes and cluster nodes. Overwrites any existing `id` values. 

**Pros**: Simple and efficient solution to create GeoJSON and VT spec compliant `id` attributes for all nodes. 
**Cons**: `id` value for a feature can change between different invocations of the API, and depends on the input GeoJSON `features`.

### PR DESCRIPTION
**Pull request by ChiefKleef**
Here is my interpretation of the discussion [here](https://github.com/mapbox/supercluster/issues/97)

I am unsure how to regenerate test data to fix the tests, can someone point me in the right direction? Is it a manual process?

I originally opened [this](https://github.com/mapbox/mapbox-gl-js/issues/8223) bug, as I was using `cluster = true` and `generateId = true` for my source specification. In this case, only the cluster points have ids, which breaks the use of setFeatureState per usual.

Closes #97.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -235,7 +232,7 @@ export default class Supercluster {
             const clusterProperties = reduce ? this._map(p, true) : null;
 
             // encode both zoom and point index on which the cluster originated
-            const id = (i << 5) + (zoom + 1);
+            const id = (i << 5) + (zoom + 1) + this.points.length;
```
Comment (mourner) [inline index.js]: If we're changing the meaning of cluster `id`, we should also change how it's decoded in methods like `getLeaves`, `getChildren` and `getClusterExpansionZoom`, otherwise those will break.

File: index.js [hunk 2]
```diff
@@ -200,10 +200,7 @@ export default class Supercluster {
                 ]],
                 tags: c.numPoints ? getClusterProperties(c) : this.points[c.index].properties
             };
-            const id = c.numPoints ? c.id : this.points[c.index].id;
-            if (id !== undefined) {
-                f.id = id;
-            }
+            f.id = c.numPoints ? c.id : (this.points[c.index].id || c.index);
```
Comment (mourner) [inline index.js]: This will break with points that have an id of `0`. Better check for `undefined`.

Comment (mourner) [reply index.js]: Also, instead of always assigning an `id`, I would put this behind an option (e.g. `generateIds`), like discussed in #97.

File: index.js (hunk 1 above)
Comment (ChiefKleef) [reply index.js]: ok will change now

Comment (mourner) [reply index.js]: `getLeaves` decodes it through `getChildren` so should be good 👍

File: index.js (hunk 2 above)
Comment (mourner) [reply index.js]: We relay the options manually in GL JS. Let's go with `generateId` though to be consistent with `geojson-vt` which already has that option.

**Comment by mourner** [comment]
@ChiefKleef hey, would you mind doing a final pass before I merge?

**Comment by robyoder** [comment]
This is a blocker for me. I'm going to fork and apply these changes, but it'd be nice to get this merged.

**Comment by asheemmamoowala** [comment]
@mourner Are the changes suggested in https://github.com/mapbox/supercluster/pull/121#pullrequestreview-248675526 required before this can merge?

**Comment by mourner** [comment]
@asheemmamoowala yes, pending removal of `yarn.lock`.

**Comment by asheemmamoowala** [comment]
@ChiefKleef , this is ready to merge except the removal of the `yarn.lock` file as mentioned above https://github.com/mapbox/supercluster/pull/121#issuecomment-526332251
