### PR TITLE
fix: prevent crash when float  is passed as `zoom` value

### LINKED ISSUE #148: Pinch zoom in Leaflet lead to "TypeError: undefined is not an object (evaluating 'tree.range')"
When pinch-zooming on leaflet I do a clusters recalculation like so:
`const clusterizedMarkers = index.getClusters(clustersBounds, zoom);
`
The zoom has sometimes non integer values coming from Leaflet:
`From my console: zoom value – 8.383082795293051`
At that moment, index.getClusters crashes the app as the zoom value is not an integer (which makes sense!)

The fix in that case is to change above code to:
`const clusterizedMarkers = index.getClusters(clustersBounds, parseInt(zoom));
`

**I'm happy with this fix and I thought it could help other but it would most probably be better to solve this directly in "supercluster" lib...**

Enjoy the weekend

### PR DESCRIPTION
**Pull request by fspoettel**
resolves #148 (I suspect followup comments after the original fix ran into this)

`zoom` is internally used to index into `trees`. some leaflet functions (e.g. `.flyTo()`) interpolate zoom values in which case calling methods like `.getClusters()` during interpolation causes a crash.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -240,7 +240,9 @@ export default class Supercluster {
     }
 
     _limitZoom(z) {
-        return Math.max(this.options.minZoom, Math.min(+z, this.options.maxZoom + 1));
+        return Math.floor(
+            Math.max(this.options.minZoom, Math.min(+z, this.options.maxZoom + 1))
+        );
```
Comment (mourner) [inline index.js:245]:
```suggestion
        return Math.max(this.options.minZoom, Math.min(Math.floor(+z), this.options.maxZoom + 1));
```

**Review by mourner — CHANGES_REQUESTED** [review]
Thank for the PR! The change makes sense — just one nit, IMO making the intent clearer.

**Review by mourner — APPROVED** [review]

File: index.js (hunk 1 above)
Comment (fspoettel) [reply index.js]: Could we use `Number.parseInt(z, 10)` directly in this case?

Comment (mourner) [reply index.js]: Yeah, not a fan of `parseInt`, and generally not a fan of excessive validation of arguments in JS libraries. `+z` is the extent I can go to for input coercion.
